### PR TITLE
Add initial autoconf script

### PR DESCRIPTION
**Pull request by vmiklos**
This avoids printing:

which: no llvm-config-3.4 in ...
which: no llvm-config-3.5 in ...
which: no clang++-3.4 in ...
which: no clang++-3.5 in ...

All the time, which is confusing as it's not an error; and the same for
clang++.

I'll merge this myself tomorrow if I see no objections.

### CODE REVIEW

**Comment by rhysd** [comment]
Looks good!  Could you also update [document](https://github.com/libclang-vim/libclang-vim#libclang-vim-installation)?

**Comment by vmiklos** [comment]
Oh, indeed.

**Comment by rhysd** [comment]
:+1:

**Comment by vmiklos** [comment]
Next on my list is to recover travis, will send an authorization request in a bit.

**Comment by rhysd** [comment]
@vmiklos I got it.  Thanks!

**Comment by vmiklos** [comment]
Hmm, I still see "Access request pending".

**Comment by rhysd** [comment]
Sorry for waiting.  I approved!

**Pull request merged**
